*** Settings ***
Documentation    Test Case 007 SWERCBJ-153. This Test Case is used to create Stored transaction without TVF
...              exist only in QA environment
Library     SeleniumLibrary
Library     BuiltIn
Library     OperatingSystem
Resource    ../../Resources/ERC_Module/ERC_Setup_Teardown.robot
Resource    ../../Resources/ERC_Module/Page_Objects/TT_Document_Page.robot
Resource    ../../Resources/ERC_Module/Page_Objects/SearchTT_Requests_Page.robot
Resource    ../../Resources/ERC_Module/Page_Objects/Login_Page.robot
Suite Setup     User to Open Browser
Suite Teardown    User to Close Browser

*** Variables ***
${TC007_SLEEP_TIMEOUT}                      0.5s
${TC007_WAITING_TIMEOUT}                    20s
${TC007_ALERT_MESSAGE_VERIFIED}             Document is verified!
${TC007_ALERT_MESSAGE_STORED}               Store operation is done.
${TC007_STORED_STATUS}                      //span[contains(text(), 'Stored')]
${TC007_STORED_STATUS_TABLE}                //tbody[@id='searchResBody']//td[@title='Stored']
${TC007_LABEL_CLASS}                        //strong[contains(text(), 'General Goods Description')]
${TC007_TAXPAYER_CODE}                      00000000000BS
${TC007_EXP_NAME}                           HMR Trading
${TC007_EXP_ADDRESS}                        HY Singa St. Avenue Cmp
${TC007_EXP_CITY}                           New Delhun
${TC007_COUNTRY}                            CI
${TC007_DEC_CODE}                           000002
${TC007_CONTACT}                            Edmundo
${TC007_PHONE}                              90012336
${TC007_EMAIL}                              dan.bacarra@webbfontaine.com
${TC007_TYPE}                               Partial
${TC007_CARRIER}                            AA
${TC007_AW_BL_CM_NO}                        LH02202
${TC007_DATE}                               01/01/2020
${TC007_FL_VO_TR_NO}                        PR-256
${TC007_TRANSPORT_NO}                       FERM EXPRESS
${TC007_MOT}                                2
${TC007_NET_MASS}                           10
${TC007_GROSS_MASS}                         10
${TC007_PLACE_LOADING}                      CIABO
${TC007_PLACE_DISCHARGE}                    BJCOO
${TC007_TOTAL_PACKING}                      10
${TC007_FCL}                                0
${TC007_LCL}                                0
${TC007_INV_REF}                            678-110
${TC007_INC}                                FOB
${TC007_CURRENCY}                           XOF
${TC007_VALUE}                              2,000.00
${TC007_MOP}                                10
${TC007_NO_OF_ITEM}                         1
${TC007_AUTOGENERATED}                      AUTO
${TC007_HSC}                                0801120000
${TC007_QTY}                                5.00
${TC007_UOM}                                KG
${TC007_PACKAGE_TYPE}                       BE
${TC007_SAVEPD_BTN}                         //a[@id= 'saveAddedItem']
${TC007_REF_NO}                             AutoSWERCBJ28
${TC007_FF}                                 FI
${TC007_FF_STYPE}                           FI Revised
${TC007_TD}                                 Transport Document
${TC007_TD_STYPE}                           LTA Revised
${TC007_DAF}                                DV

*** Test Cases ***
Test Case 007 SWERCBJ-153 Store Status Creation - Manual w/o TVF
    [Tags]    Functional
    Given Login at ERC Homepage
    When User to change the French Translation to English
    And Click Request AVD
    And In Header Tab, supply the following required fields
    And Go to Names & Parties Tab, supply the following fields:
    And Go to Transport Tab, supply the following fields:
    And Go to Financial Tab, supply the following fields:
    And Verify the field should be Auto-computed value in Financial Tab
    And Go to Goods Tab, supply the following fields
    And Go to Remarks Tab, supply the following fields:
    And Go to Attachment Tab to supply the following required fields
    And Click on Verify button to validate all required fields has been correctly supplied
    And Click Store button
    Then Successful Store Operation, messaging should be displayed and TT ID and other details should be provided
    And Searched for the newly created TT ID by entering TT ID on TT field then hit Search button


*** Keywords ***
User to change the French Translation to English
    Login_Page.ERC Page should be in English
    Login_Page.Detect Language used in ERC Page

In Header Tab, supply the following required fields
    Sleep   ${TC007_SLEEP_TIMEOUT}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_ITEMNO}  ${TC007_NO_OF_ITEM}

Go to Names & Parties Tab, supply the following fields:
    TT_Document_Page.Click Names & Parties Tab
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_IMP}     ${TC007_TAXPAYER_CODE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_IMPEMAIL}  ${TC007_EMAIL}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_IMPTEL}    ${TC007_PHONE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_EXPNAM}    ${TC007_EXP_NAME}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_EXPADD}    ${TC007_EXP_ADDRESS}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_EXPCTY}    ${TC007_EXP_CITY}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_COUNTRY} ${TC007_COUNTRY}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_DEC}     ${TC007_DEC_CODE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_CONTACT}   ${TC007_CONTACT}
    # TODO unable to input details on this field but when you do it on manual it works 404 Error message occurs on Console log - SWERCBJ-453
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_PHONENUM}     ${TC007_PHONE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_APPEMAIL}     ${TC007_EMAIL}


Input Phone Number by Input under Names and Parties Tab
    [Documentation]      This Keyword is used to input Phone Number
    [Arguments]          ${ref_no_input}
    Wait Until Element is Enabled   xpath=${ERC_DOCPAGE_INPUT_PHONENUM}    timeout=${ERC_DOCPAGE_WAITING_TIMEOUT}
    Wait Until Element is Visible   xpath=${ERC_DOCPAGE_INPUT_PHONENUM}    timeout=${ERC_DOCPAGE_WAITING_TIMEOUT}
    Sleep                          ${ERC_DOCPAGE_TIMEOUT}
    Input Text                     xpath=${ERC_DOCPAGE_INPUT_PHONENUM}    ${ref_no_input}
    Sleep                          ${ERC_DOCPAGE_TIMEOUT}
    Press Keys                     xpath=${ERC_DOCPAGE_INPUT_PHONENUM}    RETURN

Go to Transport Tab, supply the following fields:
    TT_Document_Page.Click Transport Tab
    TT_Document_Page.Select Shipment Type   ${TC007_TYPE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_COS}        ${TC007_COUNTRY}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_CARRIER}    ${TC007_CARRIER}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_BLNO}         ${TC007_AW_BL_CM_NO}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_DAT_BLDATE}         ${TC007_DATE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_VOYAGENO}     ${TC007_FL_VO_TR_NO}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_TRANSPORTNO}  ${TC007_TRANSPORT_NO}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_MOT}        ${TC007_MOT}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_NETMASS}      ${TC007_NET_MASS}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_GROSSMASS}    ${TC007_GROSS_MASS}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_PLACELOADING}  ${TC007_PLACE_LOADING}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_DISCHARGE}     ${TC007_PLACE_DISCHARGE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_TOTAL_PACKING}   ${TC007_TOTAL_PACKING}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_FCLNO}        ${TC007_FCL}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_LCLNO}        ${TC007_LCL}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_MARKS}        ${TC007_AUTOGENERATED}

Go to Financial Tab, supply the following fields:
    TT_Document_Page.Click Financial Tab
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_INVREF}        ${TC007_INV_REF}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_DAT_INV}             ${TC007_DATE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_CURRENCY}    ${TC007_CURRENCY}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_TOTALFOB}      ${TC007_VALUE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_TOTALFREIGHT}  ${TC007_VALUE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_TOTALINSURANCE}  ${TC007_VALUE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_INPUT_OTHER_CHARGES}   ${TC007_VALUE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_INC}           ${TC007_INC}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_INCITEM}       ${TC007_INC}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_TOTALINV}      ${TC007_VALUE}
    TT_Document_Page.Enter/Modify Field Details of      xpath=${ERC_DOCPAGE_SUGGEST_PAYMENT}       ${TC007_MOP}

Verify the field should be Auto-computed value in Financial Tab
    TT_Document_Page.Verify Field and Value of   xpath=${ERC_DOCPAGE_INPUT_TOTALCIF}
    TT_Document_Page.Verify Field and Value of   xpath=${ERC_DOCPAGE_INPUT_TOTALDUTIABLE}

Go to Goods Tab, supply the following fields
    TT_Document_Page.Click Goods Tab
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_GDESC}  ${TC007_AUTOGENERATED}
    TT_Document_Page.Click Add button under Goods tab
    TT_Document_Page.Enter Product Code under Goods Tab     ${TC007_HSC}
    Enter Product Description under Goods Tab               ${TC007_AUTOGENERATED}
    TT_Document_Page.Enter Incoterm Item value under Goods Tab  ${TC007_VALUE}
    TT_Document_Page.Enter Item Quantity under Goods Tab        ${TC007_QTY}
    TT_Document_Page.Enter Item Unit Measurement under Goods Tab    ${TC007_UOM}
    TT_Document_Page.Enter Item Country Of Origin under Goods Tab   ${TC007_COUNTRY}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_PACKNO}        ${TC007_NO_OF_ITEM}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_SUGGEST_PACKTYPE}    ${TC007_PACKAGE_TYPE}
    click element   xpath=${TC007_SAVEPD_BTN}
    Wait Until Page Contains Element     xpath=${TC007_LABEL_CLASS}    timeout=${TC007_WAITING_TIMEOUT}

Enter Product Description under Goods Tab
    [Documentation]  Test Step  007
    [Arguments]  ${hsc_desc_input}
    Input Text         xpath=${ERC_DOCPAGE_INPUT_HSCDESC}   ${hsc_desc_input}
    Sleep              ${ERC_DOCPAGE_TIMEOUT}
    Press Keys         xpath=${ERC_DOCPAGE_INPUT_HSCDESC}  TAB

Go to Remarks Tab, supply the following fields:
    TT_Document_Page.Click Remarks Tab
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_REMARKS}  ${TC007_AUTOGENERATED}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_REASONS}  ${TC007_AUTOGENERATED}

Go to Attachment Tab to supply the following required fields
    TT_Document_Page.Click Attachment Tab
    TT_Document_Page.Upload Files Select in Attachment Tab    ${TC007_TD}   ${TC007_TD_STYPE}   ${TC007_REF_NO}
    TT_Document_Page.Upload Files Select in Attachment Tab    ${TC007_FF}   ${TC007_FF_STYPE}   ${TC007_REF_NO}
    TT_Document_Page.Upload Files Input in Attachment Tab     ${TC007_DAF}  ${TC007_REF_NO}

Click on Verify button to validate all required fields has been correctly supplied
    TT_Document_Page.Click Verify button
    Wait Until Page Contains    ${TC007_ALERT_MESSAGE_VERIFIED}    timeout=${TC007_WAITING_TIMEOUT}

Click Store Button
    Store operation

User should successfully stored the transaction with imported .xml file
    Close the Confirmation Dialog box

Searched for the newly created TT ID by entering TT ID on TT field then hit Search button
   Wait Until Element is Visible    xpath=${ERC_DOCPAGE_TTID_LOCATOR}       timeout=${TC007_WAITING_TIMEOUT}
   element should be visible   xpath=${ERC_DOCPAGE_TTID_LOCATOR}
   ${value}=    Get Text  xpath=${ERC_DOCPAGE_TTID_LOCATOR}
   Should Not Be Empty  ${value}
   SearchTT_Requests_Page.Click Search link
   SearchTT_Requests_Page.Enter Request ID  ${value}

Verify Status for the searched TT ID will be Stored
     Wait Until Page Contains Element     ${TC007_STORED_STATUS}    timeout=${TC007_WAITING_TIMEOUT}


