*** Settings ***
Documentation    Test Case 008 SWERCBJ-412. This Test Case is used for to update and submit Queried Transactions
Library     SeleniumLibrary
Library     BuiltIn
Library     OperatingSystem
Resource    ../../Resources//ERC_Module//ERC_Setup_Teardown.robot
Resource    ../../Resources//ERC_Module/Page_Objects/TT_Document_Page.robot
Resource    ../../Resources//ERC_Module/Page_Objects/SearchTT_Requests_Page.robot
Resource    ../../Resources/ERC_Module/Page_Objects/Login_Page.robot
Suite Setup     User to Open Browser
Suite Teardown    User to Close Browser

*** Variables ***
${TC008_EXP_NAME}               HMR Trading
${TC008_EXP_ADDRESS}            HY Singa St. Avenue Cmp
${TC008_EXP_CITY}               Navotas
${TC008_EXP_COUNTRY}            PH
${TC008_CONTACT_PERSON}         Edmundo
${TC008_EMAIL}                  dan.bacarra@webbfontaine.com
${TC008_AW_BL_CM_NO}            LH02202
${TC008_AW_BL_CM_DATE}          01/01/2020
${TC008_FL_VO_TR_NO}            PR-256
${TC008_TRANSPORT_NO}           FERM EXPRESS
${TC008_MOT}                    4
${TC008_INV_REF}                2020A992-INV
${TC008_INV_DATE}               01/01/2020
${TC008_INV_CURRENCY}           XOF
${TC008_INV_TOTAL}              5,000.00
${TC008_SUGGEST_PAYMENT}        30
${TC008_AUTOGENERATED}          Auto-generated details
${TC008_TT_STATUS}              Queried
${TC008_ALERT_SUBMITTED}        Submit operation is done.


*** Test Cases ***
Test Case 008 SWERCBJ-412 Verify Update/Submit operation upon Queried status of transaction
    [Tags]    Smoke
    Given Login at ERC Homepage
    When User to change the French Translation to English
    And In Search page, open for Queried status of transaction by clicking Edit button
    And Modify the some of the details in the tabs then click Update button
    And Open again the recently Stored transaction
    And Verify the mandatory fields then click Submit button
    Then Prompt message displays that the transaction was submitted

*** Keywords ***
User to change the French Translation to English
    Login_Page.ERC Page should be in English
    Login_Page.Detect Language used in ERC Page

In Search page, open for Queried status of transaction by clicking Edit button
    SearchTT_Requests_Page.Select Status of Transaction    ${TC008_TT_STATUS}
    SearchTT_Requests_Page.Click Search button
    SearchTT_Requests_Page.Click Edit Icon button

Modify the some of the details in the tabs then click Update button
    TT_Document_Page.Click Names & Parties Tab
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_EXPNAM}        ${TC008_EXP_NAME}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_EXPADD}        ${TC008_EXP_ADDRESS}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_EXPCTY}        ${TC008_EXP_CITY}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_SUGGEST_COUNTRY}     ${TC008_EXP_COUNTRY}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_CONTACT}       ${TC008_CONTACT_PERSON}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_APPEMAIL}      ${TC008_EMAIL}
    TT_Document_Page.Click Transport Tab
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_BLNO}          ${TC008_AW_BL_CM_NO}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_DAT_BLDATE}          ${TC008_AW_BL_CM_DATE}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_VOYAGENO}      ${TC008_FL_VO_TR_NO}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_TRANSPORTNO}   ${TC008_TRANSPORT_NO}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_SUGGEST_MOT}         ${TC008_MOT}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_MARKS}         ${TC008_AUTOGENERATED}
    TT_Document_Page.Click Financial Tab
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_INVREF}        ${TC008_INV_REF}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_DAT_INV}             ${TC008_INV_DATE}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_SUGGEST_CURRENCY}    ${TC008_INV_CURRENCY}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_SUGGEST_TOTALINV}    ${TC008_INV_TOTAL}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_SUGGEST_PAYMENT}     ${TC008_SUGGEST_PAYMENT}
    TT_Document_Page.Click Goods Tab
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_GDESC}         ${TC008_AUTOGENERATED}
    TT_Document_Page.Click Remarks Tab
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_REMARKS}       ${TC008_AUTOGENERATED}
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_INPUT_REASONS}       ${TC008_AUTOGENERATED}
    TT_Document_Page.Update operation for Stored/Queried

Open again the recently Stored transaction
    SearchTT_Requests_Page.Click Search link
    SearchTT_Requests_Page.Select Status of Transaction     ${TC008_TT_STATUS}
    SearchTT_Requests_Page.Click Search button
    SearchTT_Requests_Page.Click Edit Icon button

Prompt message displays that the transaction was submitted
    [Documentation]   This keyword is to notify the user if the transaction was successfully submittted
    Prompt display message should appear
    page should contain     ${TC008_ALERT_SUBMITTED}

Verify the mandatory fields then click Submit button
    TT_Document_Page.Click Verify button
    TT_Document_Page.Click Submit button

Verify the entered details on the field was updated
    [Documentation]   This keyword is to verify details were updated on the fields after the operation
    [Arguments]  ${locator}     ${expectedString}
    ${value}=    Get Element Attribute  ${locator}   value
    Should Be Equal     ${value}    ${expectedString}
