*** Settings ***
Documentation    Test Case 008 SWVW-1015. This Test Case is used to verify the validation message for FDI-DAI Number
Library     SeleniumLibrary
Library     BuiltIn
Library     OperatingSystem
Resource    ../../Resources/ERC_Module/ERC_Setup_Teardown.robot
Resource    ../../Resources/ERC_Module/Page_Objects/TT_Document_Page.robot
Resource    ../../Resources/ERC_Module/Page_Objects/SearchTT_Requests_Page.robot
Resource    ../../Resources/ERC_Module/Page_Objects/Login_Page.robot
Suite Setup     User to Open Browser
Suite Teardown    User to Close Browser

*** Variables ***
${TC008_IMPORT_XML_FULLPATH}   ${EXECDIR}/Resources/ERC_Module/Data/TT-209300.xml
${TC008_TC_TIMEOUT}                   20s
${TC008_IMPORT_XML_ERROR_MESSAGE}     Country of supply : Country of supply cannot be empty while Port of Loading/Place of Receipt is not empty!
${TC008_ERROR_MESSAGE}                //a[@errorelementid='ctySupp']
${TC008_ALERT_MESSAGE}                FDI/DAI Number: Value is required
${TC008_CTY_SUPPLY}                   CI
${TC008_STORED_STATUS}                //span[contains(text(), 'Stored')]
${TC008_TT_ID}                        //*[@id="header"]/div/fieldset/div[1]/div/label
${TC008_MOT}                         1
${TC008_AUTOGENERATED}               Auto-generated details
${TC008_FF}                          Facture Finale
${TC008_DAI}                         DAI
${TC008_TRANSPORT_DOCUMENT}          Transport Document
${TC008_DAF}                         DAF

*** Test Cases ***
Test Case 008 SWVW-1015 Verify FDI/DAI field validation
    [Tags]    Smoke
    Given Login at ERC Homepage
    When ERC Page should be in English
    Then Detect Language used in ERC Page
    Given Creation of Stored transaction with imported FDI/DAI
    And In Search for Trade Transactions (TT) page, search for Stored transaction by selecting on the Status dropdown then click Search
    And Click Edit Icon button
    And Verify the mandatory fields in required tabs prior to submit operation
    And Click Submit button with Warning Message
    Then Prompt validation message displayed

*** Keywords ***
Creation of Stored transaction with imported FDI/DAI
    [Documentation]  Part of the precondition to start the test
    SearchTT_Requests_Page.Click Create TT link
    TT_Document_Page.Import XML File from   ${TC008_IMPORT_XML_FULLPATH}
    Wait Until Page Contains               ${TC008_IMPORT_XML_ERROR_MESSAGE}   timeout=${TC008_TC_TIMEOUT}
    Wait Until Element is Enabled    xpath=${TC008_ERROR_MESSAGE}       timeout=${TC008_TC_TIMEOUT}
    click element  xpath=${TC008_ERROR_MESSAGE}
    TT_Document_Page.Enter/Modify Field Details of  xpath=${ERC_DOCPAGE_SUGGEST_COS}  ${TC008_CTY_SUPPLY}
    TT_Document_Page.Click Store button
    TT_Document_Page.Prompt display message should appear
    Page Should Contain Element     ${TC008_STORED_STATUS}


In Search for Trade Transactions (TT) page, search for Stored transaction by selecting on the Status dropdown then click Search
   [Documentation]  Test Step 001
   Wait Until Element is Visible    xpath=${TC008_TT_ID}       timeout=${TC008_TC_TIMEOUT}
   element should be visible   xpath=${TC008_TT_ID}
   ${value}=    Get Text  xpath=${TC008_TT_ID}
   Should Not Be Empty  ${value}
   SearchTT_Requests_Page.Click Search link
   SearchTT_Requests_Page.Enter Request ID  ${value}

Verify the mandatory fields in required tabs prior to submit operation
    [Documentation]  Test Step 002
    TT_Document_Page.Click Attachment Tab
    TT_Document_Page.Input Doc Type under Attachments Tab            ${TC008_FF}
    TT_Document_Page.Input Reference Number under Attachments Tab    ${TC008_AUTOGENERATED}
    TT_Document_Page.Upload and Add File under Attachments Tab
    TT_Document_Page.Input Doc Type under Attachments Tab            ${TC008_DAI}
    TT_Document_Page.Input Reference Number under Attachments Tab    ${TC008_AUTOGENERATED}
    TT_Document_Page.Upload and Add File under Attachments Tab
    TT_Document_Page.Input Doc Type under Attachments Tab            ${TC008_TRANSPORT_DOCUMENT}
    TT_Document_Page.Input Reference Number under Attachments Tab    ${TC008_AUTOGENERATED}
    TT_Document_Page.Upload and Add File under Attachments Tab
    TT_Document_Page.Input Doc Type under Attachments Tab            ${TC008_DAF}
    TT_Document_Page.Input Reference Number under Attachments Tab    ${TC008_AUTOGENERATED}
    TT_Document_Page.Upload and Add File under Attachments Tab
    TT_Document_Page.Click Header Tab
    Clear Element Text  xpath=${ERC_DOCPAGE_FDI-DAI_NO}
    TT_Document_Page.Click Transport Tab
    TT_Document_Page.Enter/Modify Field Details of     xpath=${ERC_DOCPAGE_SUGGEST_MOT}  ${TC008_MOT}

Prompt validation message displayed
    Wait Until Page Contains    ${TC008_ALERT_MESSAGE}   timeout=${TC008_TC_TIMEOUT}

